FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN rm -rf node_modules package-lock.json && npm install

# Copy source
COPY . .

EXPOSE 3002

# Run dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3002"]
